### ISSUE TITLE
无法正常使用报错如下所示

### ISSUE THREAD

**Issue by xxsmile123** [ZororoZ/fscanOutput#2]
0.5版本的
![图片](https://user-images.githubusercontent.com/43473886/175779821-8fe7cead-c5fa-4a2c-9563-7374bd391c1b.png)
1.0.2版本的
![图片](https://user-images.githubusercontent.com/43473886/175779857-74cee703-a976-4b0c-8521-0a6f5627791a.png)

python版本：python 3.8.7

**Comment by xxsmile123** [comment]
打包成exe程序吧，师傅。不然还得考虑依赖啥的。

**Comment by ZororoZ** [comment]
Brother，这是你文件fsan导出的txt文件的格式问题，你这编码不是utf-8 ，工具里的是utf-8解码的，你看报错信息  utf-8  解不开。你把 resault.txt另存为utf-8格式就行了 
![image](https://user-images.githubusercontent.com/46238787/175874481-2794daf3-3434-41dd-a2a0-6ddcf4ef88fc.png)

**Comment by xxsmile123** [comment]
解决了，感谢师傅
