### ISSUE TITLE
redis漏洞输出显示like

### ISSUE THREAD

**Issue by ThestaRY7** [ZororoZ/fscanOutput#8]
fscan扫出来是：
[+] Redis:192.168.1.1:6379 like can write /var/spool/cron/
到了表格就变成了
192.168.1.1	Redis	like
可以加个判断，如果内容是like，则选择整一段字符串。

**Comment by ZororoZ** [comment]
有想过这样修改，但是不排除有密码确实为like，下一版修改中会对此处尝试做优化，请持续关注
